apiVersion: apps/v1
kind: Deployment
metadata:
  name: dennisfischpro690finaldeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dennisfischpro690final
  template:
    metadata:
      labels:
        app: dennisfischpro690final
    spec:
      containers:
      - name: dennisfischpro690finalcontainer
        image: dennisfischpro690final.azurecr.io/node:12.18.1
        ports:
        - containerPort: 3000 
