apiVersion: apps/v1
kind: Deployment
metadata:
  name: dennisfischpro690finaldeployment
  annotations:
    argo-rollouts/strategy: "BlueGreen"
    argo-rollouts/blueGreen: '{"activeService": "dennisfischpro690final", "previewService": "dennisfischpro690final-preview"}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dennisfischpro690final
  template:
    metadata:
      labels:
        app: dennisfischpro690final
    spec:
      containers:
      - name: dennisfischpro690finalcontainer
        image: dennisfischpro690final.azurecr.io/node:12.18.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 
