apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dennisfischpro690finalrollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dennisfischpro690finalrollout
  template:
    spec:
      containers:
      - name: dennisfischpro690finalapprolloutcontainer
        image: dennisfischpro690final.azurecr.io/node:12.18.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: dennisfischpro690finalservice
      previewService: dennisfischpro690finalpreviewservice
      autoPromotionEnabled: false